### PR TITLE
Formatting and fixing build errors

### PR DESCRIPTION
**Pull request by nathantheinventor**
This branch has two major changes:

1. Formatting the source code to make it more readable. I used Eclipse's automatic format tool to allow consistency across the code base. For example, tabs were replaced, braces are placed consistently, and empty lines have spaces on them.
2. Get it to build properly. The code had some absolute paths that were breaking the build on my computer, and there were some missing semi-colons and missing std:: specifiers.

### CODE REVIEW

**Comment by wwoodham** [comment]
Nice!
Thanks Nathan.

**Comment by cshean** [comment]
Thanks for doing that Nathan. I was doing some work on the compass and removed a using namespace std statement (because I don't think we should be including those) but forgot to prefix string with std::. I merged your changes.

**Comment by cshean** [comment]
The only thing I would say is that those pyc files that you deleted really didn't need to be. They are auto generated and rewritten by the python code every time you run catkin-make and rerun ROS, so there's no need to delete them in the future

**Comment by nathantheinventor** [comment]
@cshean I removed the pyc files for two reasons:

1. Philosophy: source control is supposed to store source and not any built files
2. Practicality: I've had major issues in the past with pyc files compiled on one machine not working on another.

**Comment by cshean** [comment]
That's fair. Unless you set up ROS on your own computer, I highly doubt we'll be running this program on any other machine than the one on the robot, so practically speaking it probably wasn't necessary, but point one is valid for sure. You finding your way around the code more now?

**Comment by nathantheinventor** [comment]
Mostly. I still need to spend a lot more time understanding how it works, but I think I've got a general idea of how it's laid out

**Comment by cshean** [comment]
I emailed Nathan Woehr and he said he really didn't remember much about the code, but I find that hard to believe honestly haha probably just doesn't want to bother. Anyways, from what I understand about it, most of the code deals in subscribers and publishers. Each node has its own channel which it publishes to, and that node can subscribe to other nodes publishing information. Based on the information received, each node processes the data and pushes it back out to the stream. I'm not really sure if there is a central driving hub where all of the information is centrally processed from, I don't really think there is. I probably will have time Tuesday night to work on the code in the science annex if you have time then. If not then, we should do something soon together

**Pull request merged**
